//! Build-time schema codegen (plan.md Phase 1a).
//!
//! Reads the pinned `schemas/schema-<version>.json` and emits typed
//! static tables for the simplest, append-mostly subtrees of the
//! schema. These replace runtime `serde_json::from_str` work that
//! adds ~80–120 ms to startup on `valid_headers`-sized datasets.
//!
//! Emitted tables (see `write_formats`/`write_entities`/`write_modalities`):
//!   * `objects.formats` — name + regex pattern + display name.
//!   * `objects.entities` — entity name/key metadata.
//!   * `rules.modalities` — modality → datatype membership.
//!
//! Each is pure, append-mostly data, cheap to serialize as a
//! `&'static [...]`.
//!
//! Generated artifacts: `$OUT_DIR/generated_{formats,entities,modalities}.rs`,
//! included by `src/lib.rs` via `include!`. The runtime
//! `schema().objects.*` API is preserved (still IndexMap-shaped for
//! serde) — these are *separate*, faster paths the anchored-regex cache
//! and selector evaluator can use.
//!
//! NOTE: these tables are emitted from the *raw* on-disk schema, before
//! the runtime patch layer in `src/patches.rs` runs. A schema patch that
//! mutates `objects.formats`, `objects.entities`, or `rules.modalities`
//! would NOT reach these static tables — such a patch must be applied
//! here in `build.rs` too. Today's only patch touches `rules.sidecars`,
//! which is not emitted statically, so the raw/patched split is safe.
//!
//! Adding more tables (columns, …) is the same shape: read the JSON
//! subtree, emit a `&'static [...]` slice, expose a `pub fn
//! *_static() -> &'static [...]`.

use std::env;
use std::fs;
use std::path::PathBuf;

const SCHEMA_REL: &str = "../../schemas/schema-1.2.1.json";

fn main() {
    println!("cargo:rerun-if-changed={SCHEMA_REL}");
    println!("cargo:rerun-if-changed=build.rs");

    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let schema_path = manifest_dir.join(SCHEMA_REL);
    let text = fs::read_to_string(&schema_path)
        .unwrap_or_else(|e| panic!("failed to read schema at {schema_path:?}: {e}"));
    let schema: serde_json::Value =
        serde_json::from_str(&text).expect("schema-1.2.1.json failed to parse at build time");

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    write_formats(&schema, &out_dir.join("generated_formats.rs"));
    write_entities(&schema, &out_dir.join("generated_entities.rs"));
    write_modalities(&schema, &out_dir.join("generated_modalities.rs"));
}

fn write_modalities(schema: &serde_json::Value, dest: &std::path::Path) {
    let mut out = String::new();
    out.push_str(
        "// AUTO-GENERATED by build.rs from rules.modalities. Edit the schema, not this file.\n\n",
    );
    out.push_str("/// `(datatype, modality)` pairs — one per datatype that belongs to a\n");
    out.push_str("/// modality. Linear scan from `bids-schema-codegen::modality_of`.\n");
    out.push_str("pub static MODALITY_OF: &[(&str, &str)] = &[\n");
    let modalities = schema
        .get("rules")
        .and_then(|r| r.get("modalities"))
        .and_then(|m| m.as_object())
        .expect("rules.modalities missing");
    let mut pairs: Vec<(&str, &str)> = Vec::new();
    for (modality, def) in modalities {
        let Some(datatypes) = def.get("datatypes").and_then(|v| v.as_array()) else {
            continue;
        };
        for dt in datatypes {
            if let Some(name) = dt.as_str() {
                pairs.push((name, modality));
            }
        }
    }
    pairs.sort();
    for (dt, modality) in pairs {
        out.push_str(&format!(
            "    ({dt}, {m}),\n",
            dt = rust_str_lit(dt),
            m = rust_str_lit(modality),
        ));
    }
    out.push_str("];\n");
    fs::write(dest, out).expect("failed to write generated_modalities.rs");
}

fn write_entities(schema: &serde_json::Value, dest: &std::path::Path) {
    let mut out = String::new();
    out.push_str(
        "// AUTO-GENERATED by build.rs from objects.entities. Edit the schema, not this file.\n\n",
    );
    out.push_str("/// `(long-key, short-name, format-name)` for each entity. Used by\n");
    out.push_str("/// `entity_short_name` / `entity_by_short_name` so those lookups\n");
    out.push_str("/// don't go through the JSON-deserialized `Schema.objects.entities`\n");
    out.push_str("/// `IndexMap` (saves ~16 entries × per-call overhead).\n");
    out.push_str("pub static ENTITIES: &[(&str, &str, &str)] = &[\n");
    let entities = schema
        .get("objects")
        .and_then(|o| o.get("entities"))
        .and_then(|e| e.as_object())
        .expect("objects.entities missing or wrong shape");
    // Preserve insertion order so callers see the same order as the
    // JSON (the entity-order matters for `FILENAME_MISMATCH`
    // reconstruction via `rules.entities`).
    for (long, def) in entities {
        let short = def.get("name").and_then(|v| v.as_str()).unwrap_or("");
        let format = def.get("format").and_then(|v| v.as_str()).unwrap_or("");
        out.push_str(&format!(
            "    ({l}, {s}, {f}),\n",
            l = rust_str_lit(long),
            s = rust_str_lit(short),
            f = rust_str_lit(format),
        ));
    }
    out.push_str("];\n");
    fs::write(dest, out).expect("failed to write generated_entities.rs");
}

fn write_formats(schema: &serde_json::Value, dest: &std::path::Path) {
    let mut out = String::new();
    out.push_str(
        "// AUTO-GENERATED by build.rs from objects.formats. Edit the schema, not this file.\n\n",
    );
    out.push_str("/// `(rule-key, regex source, display-name)` for each `objects.formats.<k>`.\n");
    out.push_str("/// Anchored `^…$` regexes are built at runtime from these patterns by\n");
    out.push_str("/// `bids-core::metadata::anchored_format_regexes` and similar helpers.\n");
    out.push_str("pub static FORMATS: &[(&str, &str, &str)] = &[\n");

    let formats = schema
        .get("objects")
        .and_then(|o| o.get("formats"))
        .and_then(|f| f.as_object())
        .expect("objects.formats missing or wrong shape");

    let mut entries: Vec<(&String, &serde_json::Value)> = formats.iter().collect();
    entries.sort_by(|a, b| a.0.cmp(b.0));
    for (name, def) in entries {
        let pattern = def
            .get("pattern")
            .and_then(|p| p.as_str())
            .unwrap_or_default();
        let display = def
            .get("display_name")
            .and_then(|d| d.as_str())
            .unwrap_or("");
        out.push_str(&format!(
            "    ({n}, {p}, {d}),\n",
            n = rust_str_lit(name),
            p = rust_str_lit(pattern),
            d = rust_str_lit(display),
        ));
    }

    out.push_str("];\n");
    fs::write(dest, out).expect("failed to write generated_formats.rs");
}

/// Emit a Rust string literal with `\` and `"` escaped. Patterns
/// already use forward slashes / digits / brackets which don't need
/// escaping.
fn rust_str_lit(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for ch in s.chars() {
        match ch {
            '\\' => out.push_str(r"\\"),
            '"' => out.push_str(r#"\""#),
            '\n' => out.push_str(r"\n"),
            '\r' => out.push_str(r"\r"),
            '\t' => out.push_str(r"\t"),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}
